project: 
  type: website
  output-dir: docs

website:
  title: "Oleson Lab Resources"
  navbar:
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: litera
    page-layout: full
    link-external-newwindow: true
    code-fold: true
    code-overflow: wrap
    code-annotations: hover
    smooth-scroll: true
    toc: true
    grid: 
      body-width: 900px
    toc-depth: 4
    toc-location: left
